title: Proud Bisaya Bai
email: proudbisayabai22@gmail.com
phone: 0915 818 4329
description: >- # this means to ignore newlines until "baseurl:"
  Proud Bisaya Bai is your Bisaya Ultimate Travel Blog which was founded last July 22, 2020 to showcase bucket-list worthy places, not only limited to Cebu but to places who speak the Language

address:
  street: Englis Vrama Street Guadalupe
  city: Cebu City
  province: Cebu
  zip: 6000
  country: Philippines



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://proudbisayabai.ph" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: proudbisayabai
github_username:  linkmalloc
url_sitemap: "https://proudbisayabai.ph"

exclude:
  - Gemfile
  - images/PBB
  - images/posts
  - images/3000x1144
  - images/ads
  - s3sync
  - serve
  - README.md



# Build settings
theme: minima

# minima theme settings
show_excerpts: false # set to true to show excerpts on the homepage

# shorten build times by only generating documents and pages that were updated
# incremental: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss


facebook: https://www.facebook.com/proudbisayabai
instagram: https://instagram.com/proudbisayabai/
twitter: https://twitter.com/Proudbisayabai/
youtube: https://www.youtube.com/channel/UCfVuNpZ2yr3OsVVkYojUsUg

author:
  name: PBB Admin
  url: https://www.facebook.com/proudbisayabai
  description: Proud Bisaya Bai is your Bisaya Ultimate Travel Blog which was founded last July 22, 2020 to showcase bucket-list worthy places, not only limited to Cebu but to places who speak the Language.
  posts_count: 100
  facebook: https://www.facebook.com/proudbisayabai
  twitter: https://twitter.com/Proudbisayabai/
  instagram: https://instagram.com/proudbisayabai/

hi: We're Proud Bisaya Bai
we_are: your Bisaya Ultimate Travel Blog which was founded last July 22, 2020 to showcase bucket-list worthy places, not only limited to Cebu but to places who speak the Language.


plugins:
  - jekyll-seo-tag
  - jekyll-lazy-load-image
  - jekyll-minifier


s3_public: https://pbb-images.s3.us-east-2.amazonaws.com
cloudfront: https://d3hukd8e3cn3kb.cloudfront.net

lazy_load_image:
  src_attr_name: data-src # [required] You need to specify the attributes to be saved for lazy loading
  preload_image: https://d3hukd8e3cn3kb.cloudfront.net/images/shimmer.gif # [optional] you can add a data uri or loading image as fallback src
  class_attr_values: # [optional] if you want to add custom class value, please add values
    - lazyload
  ignore_selectors: # [optional] if you want to ignore applying lazy load image, please add selector (css or xpath)
    - ".ignore-lazy-image-load"
  #   - "/*[@class='ignore-lazy-image-load']"
  additional_attrs: # [optional] if you want to add attributes, please add key value
    "data-size": auto
    "loading": "lazy"

jekyll-minifier:
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  uglifier_args:
    harmony: true
  exclude:
    - 'admin/dashboard.js'
    - 'admin/dashboard.html'
    - 'admin/tutorial.js'
