title: Proud Bisaya Bai
email: proudbisayabai.linkmalloc@gmail.com
phone: 0915 818 4329
description: >- # this means to ignore newlines until "baseurl:"
  Proud Bisaya Bai is your Bisaya Ultimate Travel Blog which was founded last July 22, 2020 to showcase bucket-list worthy places, not only limited to Cebu but to places who speak the Language

address:
  street: Englis Vrama Street Guadalupe
  city: Cebu City
  province: Cebu
  zip: 6000
  country: Philippines



baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: proudbisayabai
github_username:  linkmalloc



# Build settings
theme: minima

# minima theme settings
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss


facebook: https://www.facebook.com/proudbisayabai
instagram: https://instagram.com/proudbisayabai/
twitter: https://twitter.com/Proudbisayabai/
youtube: https://www.youtube.com/channel/UCTOmZBxmfYl31jhzIrre5hQ

author:
  name: PBB Admin
  url: https://www.facebook.com/proudbisayabai
  description: >- # this means to ignore newlines until "baseurl:"
Proud Bisaya Bai is your Bisaya Ultimate Travel Blog which was founded last July 22, 2020 to showcase bucket-list worthy places, not only limited to Cebu but to places who speak the Language
  
  posts_count: 100
  facebook: https://www.facebook.com/proudbisayabai
  twitter: https://twitter.com/Proudbisayabai/
  instagram: https://instagram.com/proudbisayabai/