backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", default: ["destination"], required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"], required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Read Time", name: "read_time", widget: "string", required: false}
      - {label: "Views", name: "views", widget: "string", default: "10", required: false}
      - {label: "Image 1000 x 600", name: "img_big_1000x600", widget: "string", required: false}
      - {label: "Image 3000 x 1144", name: "img_big_3000x1144", widget: "string", required: false}
      - {label: "Image 500 x 500", name: "img_500x500", widget: "string", required: false}
      - {label: "Article Image 1 - 500x500", name: "img_500_1", widget: "string", required: false}
      - {label: "Article Image 2- 500x500", name: "img_500_2", widget: "string", required: false}
      - {label: "Article Image 3- 500x500", name: "img_500_3", widget: "string", required: false}
      - {label: "Article Image 4- 500x500", name: "img_500_4", widget: "string", required: false}
      - {label: "Article Image 5- 500x500", name: "img_500_5", widget: "string", required: false}

  ##  meta: # Meta data fields. Just like fields, but without any preview element
   ##   - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}